'use client'
import { SessionProvider, useSession } from 'next-auth/react'
import './globals.css'
import Head from 'next/head'
import Link from 'next/link'
import TopbarDropdown from './components/Dropdown'
import { Session } from 'next-auth'
import { useEffect } from 'react'
import { useStore } from '../stores/UserStore'
import { TourProvider, useTour } from '@reactour/tour'
import { useRouter } from 'next/router'
import RightSidebar from './components/Rightsidebar'


// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <TourProvider 
      beforeClose={async () => {
        await fetch('/api/tutorial',{
          method: 'POST',
          headers: {
            'Content-Type': 'application/json'
          },
          body: JSON.stringify({
            completed: true
          })
        })
      }}
      styles={{
        badge: (base) => ({
          ...base,
          backgroundColor: 'rgb(239, 68, 68)',
        }),
        dot: (base,state) => {
          console.log('state', state, base)
          return{
            ...base,
            backgroundColor: state.current ? 'rgb(239, 68, 68)' : '',
          }
        },
      }}
      steps={steps}>
      <SessionProvider >
      <body
      className='px-8 py-5'
      >
      <div
      className='flex flex-row'
      >
      <TopBar />
      <RightSidebar
       />
      </div>
        {children}
        </body>
      </SessionProvider>
      </TourProvider>
    </html>
  )
}

const steps = [
  {
    selector: '.navigation',
    content: 'This is where you can navigate to different pages',
  },
  {
    selector: ".chatbot",
    content: "This is where you can chat with the chatbot. You can ask it questions about the app,or ask it about topics in neuroscience, AI, machine learning, and more!",
  },
  {
    selector: ".profile",
    content: "This is where you can view your profile, and edit your profile information, and logout.",
  }
]

function TopBar(){
  return (
    <div
      className='flex flex-col w-fit navigation'
      >
       <Link
        href="/"
       className='flex flex-row items-center'
       >
       <img 
          className="w-20 h-20 rounded-full"
        src="https://synesthesia-public.s3.amazonaws.com/synapMeLogo.png" alt="SynapMe Logo" />
        <div>
          <h1 className="text-3xl font-bold ml-4">SynapMe</h1>
        </div>
       </Link>
       
       <Link
        href="/users"
        className='text-gray-500 mt-4 hover:text-gray-600 font-semibold text-lg ml-4'
        >
          Users
        </Link>

      </div>
  )
}


